EliasEsperanza/Proyeccion-Social

app/Http/Controllers/EstadoController.php, app/Models/Estado.php, app/Models/Proyecto.php
correccion a modelo Proyecto y Estado
=> Correcciones

app/Http/Controllers/AsignacionController.php, app/Models/Asignacion.php
arreglo del controller y del modelo
=> asignacion

app/Http/Controllers/EstudianteController.php
=> New angel branch

app/Http/Controllers/ChatDocumentoController.php
Tarea numero #2 ChatDocumentoController -> Integración con sistema de notificaciones.
Paginación de resultados. lista para ser revisada.
=> Rama josue

resources/views/layouts/app.blade.php, resources/views/layouts/gestion-de-roles.blade.php, routes/web.php
=> vista de gestion de roles

database/seeders/AsignacionesSeeder.php, database/seeders/DatabaseSeeder.php
Creacion de seeder para la tabla Asignaciones
=> Creacion de seeder para la tabla Asignaciones

routes/web.php
Modificación de endpoint a modo vistas
=> William Vásquez

app/Http/Controllers/EstudianteController.php, app/Http/Controllers/ProyectoController.php, routes/web.php
este es un pull request de EstudianteController y ProyectoController
=> Stevendevs

routes/web.php
enponint chat documentos y departamentos
=> "Endpoint"

database/seeders/HorasSocialesSeeder.php
insertando datos en la tabla de horas sociales
=> Creando datos de la tabla 'Horas Sociales'

database/seeders/AsignacionesSeeder.php
Es una nueva creación del Seeder, ya extrae el id de estudiantes, el id de Proyectos y obtiene los usuarios con el rol de Tutor.
itera sombre cada estuantes para hacer la asignación 
asigna un proyecto aleatorio 
obtiene el Id del estudiante actual
asigna un tutor aleatorio
asigna la fecha en
=> Nueva creacion en el AsinacionSeder

.env, config/filesystems.php, database/seeders/AsignacionesSeeder.php, database/seeders/EstudianteSeeder.php, public/storage/.gitignore
Creación del Link simbólico para almacenar archivos, Modificación en la config/filesystem.php, para que sea public el disco, por defecto, y en el archivo .env modifique el " FILESYSTEM_DISK=public   " se dejo como public para que el almacenamiento de archivos utilice el disco public
'default' => env('FILESYSTEM_DISK', 'public'),//aquí también se dejo como public
=> Aracely dev

app/Http/Controllers/DocumentoController.php
esta modificacion permitira subida de archivo con validacion de formato y la descarga de estos
=> Modificacion de documentoController

database/seeders/AsignacionesSeeder.php
Actualización en seeder De Asignaciones
=> actualizacion en seederAsignaciones

app/Http/Controllers/AuthController.php
implementando la generacion y validacion de tokens JWT en cada metodo creado
=> creacion de AuthController.php

app/Http/Middleware/JwtAuthMiddleware.php, app/Http/Middleware/RoleMiddleware.php, routes/web.php
Tarea terminada, lista para revisión por parte del jefe
=> subiendo tarea nueva

app/Http/Controllers/registerYloginController.php, app/Http/Requests/LoginRequest.php, app/Http/Requests/RegisterRequest.php
**Controlador de validacion de datos en el registro y login
**Creacion de RegisterRequest y LoginRequest para la validacion
=> creacion request clases para validaciones

app/Http/Controllers/ProyectoController.php, public/css/gestor-de-TI.css, public/css/solicitud-proyecto.css, resources/views/layouts/app.blade.php, resources/views/proyecto/gestor-de-TI.blade.php, resources/views/proyecto/solicitud-proyecto.blade.php, routes/web.php
Nuevas Vistas 
Solicitud de Proyecto y 
Gestor de TI
=> Nuevas Vistas Solicitud de Proyecto y Gestor de TI

app/Http/Controllers/ProyectoController.php, public/css/estudianteprincipal.css, public/css/proyecto-disponible-list.css, resources/views/estudiantes/dashboard.blade.php, resources/views/proyecto/proyecto-disponible-list.blade.php, routes/web.php
Nueva vista Lista de de proyectos
=> Nueva vista Lista de de proyectos

app/Http/Controllers/ProyectosEstudiantesController.php, resources/views/layouts/appE.blade.php, routes/web.php
Solo falta el inicio que esa ruta da error, no se porque
=> Ruteo de vistas estudiantes

app/Http/Controllers/ProyectosEstudiantesController.php, resources/views/estudiantes/detallesmio.blade.php, resources/views/estudiantes/proyectomio.blade.php
implementado consumo de api para las vistas detallesmio.blade y proyectomio.blade
=> Kevin branch

database/seeders/DocumentosSeeder.php
=> Nuevos Documentos

app/Http/Controllers/ProyectoController.php, resources/views/estudiantes/proyecto-disponibles.blade.php, resources/views/layouts/appE.blade.php, resources/views/proyecto/proyecto-disponible-list.blade.php
para realizar el filtrado de las vista de dashboard estudiante, se realizo modificaciones en el controller de proyecto para poder realizar el filtrado correspondiente y que se mostraran solo los poryectos dependiendo de las sección o departamento a la que el estudiante pertenezca, se realizo una pequela modificacion para poder cargar el perfil de estudiante y comprobar que se estaba recibiendo un auth, para poder autenticar la seccion a la que pertenece el estudiante y de esta manera filtrar correctamente  que se muestren los poryectos se modificaron unicamente 4 archivos que fueron los necesarios para realizar el filtrado proyecto-disponible.blade.php de la carpeta estudiante, appE.blade.php, proyecto-disponible-list.blade.php de la carpeta proyecto y proyectocontroller.php en las …
=> Williams dev- Filtrado de proyectos segun seccion o departamento 

public/js/login.js, public/js/registro.js, resources/views/proyecto/gestor-de-TI.blade.php
tambien van los cambios de loginn.js y registro.js de la validacion del correo
=> Lino branch

app/Http/Controllers/EstudianteController.php, resources/views/estudiantes/solicitud-proyecto.blade.php, resources/views/proyecto/solicitud-proyecto-coordinador.blade.php, routes/web.php
*agregado ruta para consumo de api de nombre de alumnos
*funcion obtener nombreEstudiante por id
*fix de funcion para cargar listado de estudiantes
* corregido diseno de blade solicitud-proyecto-coordinador (queda mostrar nombre de estudiantes)
=> implementaciones varias

app/Http/Controllers/ProyectoController.php, resources/views/proyecto/VerdetallesSolicitud.blade.php, resources/views/proyecto/solicitud-proyecto-coordinador.blade.php, routes/web.php
se modifico proyceto controller, web para correcion de las rutas y verdetallesblade y proyectos coordinador
=> ya esta la visa se solicitudes uncionando al 100

app/Http/Controllers/ProyectoController.php, app/Http/Controllers/ProyectosEstudiantesController.php, resources/views/estudiantes/detallesmio.blade.php, resources/views/estudiantes/proyectomio.blade.php, resources/views/gestionProyectos/gestionProyectos.blade.php
*arreglo get de detalles de proyecto de estudiante
*cambio a display de fecha del bladedetallesmio y proyectomio
*ajuste blade gweeestioProyecto
=> arreglos varios

app/Http/Controllers/ProyectoController.php
Modificacion ProyectoController
=> Modificacion ProyectoController

resources/views/layouts/appE.blade.php, resources/views/usuarios/perfilUsuario.blade.php
se realizo la integración para poder acceder a perfil en la vista estudiante y el filtrado de los proyectos únicamente de la sección a la que pertenezca el estudiante
=> cambios en perfil de estudiante y filtrado

app/Http/Controllers/ProyectoController.php, resources/views/proyecto/VerdetallesSolicitud.blade.php, resources/views/proyecto/solicitud-proyecto-coordinador.blade.php
+modificacion funcion get de detalles dfuncion para hacer la relacion estudiante_usuario
+se modifico blade detalles para mostrar los datos de [departamento, esstudiantes asociados, nombre del proyecto ]
=> arreglando blade detalles solicitud

app/Http/Controllers/ProyectoController.php, resources/views/estudiantes/proyecto-disponibles.blade.php, routes/web.php
- agregar id de estudiantes a un proyecto en fase de solicitud
- se agrego una funcion solo para asignar a tabla pivote y pdate a proyecto para cambiar estado
- modificado blade proyecto-disponible para hacer el post correctamente (falta hacer funcionar elos btn borrar de los item list)
- agregado ruta para ela funcion nueva
=> implementado insert de estudiante a proyecto en tabla pivot

app/Http/Controllers/ProyectosEstudiantesController.php, resources/views/estudiantes/dashboard.blade.php, resources/views/estudiantes/proyectomio.blade.php
- agregado warnings en caso [no encunta estudiante, ya posee proyecto]
- agregado el warning a blade dashboard
- agregado condicional para cuando no se tenga tutor asignado aun
- corregido error por caso de dividir entre 0 para el porcentaje completado de hr
=> Arreglos menores

app/Http/Controllers/EstudianteController.php, app/Http/Controllers/UserController.php, app/Models/User.php
* filtramos usuarios y tutores que compartan el departamento del coordinador y los listamos en los usuarios
=> configuracion filtro usuario para coordinadores

app/Http/Controllers/UserController.php
* al copiar el codigo de filtro de coordinador accidentalmente sobreescribi parte del codigo original de otros filtros pero ya se corrigio
=> correcion del metodo list

resources/views/layouts/app.blade.php, resources/views/layouts/appE.blade.php, resources/views/usuarios/perfilUsuario.blade.php
-se corrigio el error que no cargaba el script de  actpassperfil.js [no habia un @Yield('script') en los diferentes app]
-se agregaron los @yield('script') para pasar scripts en diferentes blades
=> FIX  de issue #279

resources/views/estudiantes/proyecto-disponibles.blade.php, resources/views/gestionProyectos/gestionProyectos.blade.php, resources/views/proyecto/proyecto-disponible.blade.php
- se modifico el blade gestion proyectos para que no deje enviar form hasta que todos los campos esten completos (por la forma de agregar estudiantes), y se agrego la alerta para dar feedback
=> fix en asignar proyectos

public/css/login.css, public/js/login.js, resources/views/login/login.blade.php
Creacion del un preloader para animacion de carga cuando se envie los datos del formulario. falta implementacion
=> Html, css de el PRELOADER

public/css/appE.css, public/css/documentos-sociales.css, public/css/style_process.css, resources/views/estudiantes/docs_tramites.blade.php, resources/views/estudiantes/documentos-sociales.blade.php
Cambios en el documentos-sociales.blade para que el ultimo card aparezca centrado.
Cambios en todo el html y css de docs_tramites.blade para que las dos paginas de documentos tengan el mismo estilo
Cambios en el css de appE para hacer que la barra lateral permanezca fija aunque se haga scroll para abajo aun faltan cambios para detalles en appE.
=> Cambiosssssssssssss

resources/views/estudiantes/dashboard.blade.php, resources/views/layouts/appE.blade.php, routes/web.php
- se arreglo para redirigir a estudiantes.documentos-sociales
=> fix de <a> ver mas

resources/views/estudiantes/dashboard.blade.php
Fix en <a> de documentos que no descargaban
=> FIX DOCUMENTOS

public/css/estudianteprincipal.css
responsividad de las card, y si el texto es grande se reduce
=> arreglo de las  card

public/css/appE.css, public/css/style_process.css, resources/views/estudiantes/vista_procesos_horas.blade.php
arreglo del blade vista_procesos_horas.blade  y su respectic=vo css style_process.css y edicion para la barra lateral se quede fija aunque haya scroll para abajo
=> Arreglo de proceso de horas sociales blade y arreglo de barra lateral

resources/views/layouts/app.blade.php
=> arreglando para que le pueda mostra los proyecto disponibles a el tutor

public/css/app.css, public/css/appE.css, resources/views/layouts/app.blade.php, resources/views/layouts/appE.blade.php
- modificado iconos y nombres de opciones para hacerlo mas desccriptivo
- estilo de nombre del proyecto
=> Retoques a blades dashboards

app/Http/Controllers/ProyectosEstudiantesController.php, public/css/app.css, public/css/appE.css, public/css/mensaje.css, resources/views/estudiantes/actualizar-horas.blade.php, resources/views/estudiantes/dashboard.blade.php, resources/views/estudiantes/detallesmio.blade.php, resources/views/estudiantes/proyectomio.blade.php
- cambio a funcion Detalles_proyecto() para integrar la barra de porcentaje
- ajuste en estilo del Titulo del navbar
-cambio en blade mensajes para que el chat no tome mas espacio de 100vh
- ajuste en limite de horas que se pueden solicitar en blade actualizar-horas
-
=> correcciones varias

public/css/app.css, public/css/appE.css, resources/views/estudiantes/detallesmio.blade.php, resources/views/gestionProyectos/gestionProyectos.blade.php, resources/views/proyecto/proyecto-disponible.blade.php
- se ajusto color del titulo del navbar
- se modifico blade detalles mio para mostrar el historial
- se agrego validacion de datos al form asignar proyecto
- se modifico <td> de descripcion de proyecto para que solo muestre una parde de la descripcion
-
=> ajustes varios

app/Http/Controllers/ProyectoController.php, resources/views/proyecto/proyecto-general.blade.php
- se modifico la funcion aprobarSolicitud para validar cada busqueda y y calculo de porcentaje completado
- se modifico tabla para mostrar el porcentaje de progreso del proyecto
=> correciones varias

public/css/mensaje.css, resources/views/layouts/app.blade.php
- se corrigio la altura ya que el div de mensaje aparecia oculto
=> fix en div chat

app/Http/Controllers/HistoriaHorasActualizadaController.php, app/Http/Controllers/ProyectoController.php, app/Http/Controllers/ProyectosEstudiantesController.php, app/Models/HistoriaHorasActualizada.php, resources/views/estudiantes/detallesmio.blade.php, resources/views/proyecto/proyecto-disponible.blade.php
+ se agrega modelo de la tabla Historial Horas Actualizadas
+ se ageraga controller con funciones basicas
+modifica la vista para mostrar datos del historial
=> Historial de horas

app/Http/Controllers/registerYloginController.php, app/Http/Middleware/ValidacionLoginContraseña.php, composer.lock, routes/web.php
Validación de contraseña login
DEBE MOSTRAR RETROALIMENTACION EN TODOS LOS CASOS  tuve ayuda de giselle hernandez
=> creacion de middlewares de login

app/Http/Middleware/SecurityMiddleware.php, resources/views/Malisioso.blade.php, routes/web.php
- se modifico para que no interfiera con las consultas legitimas
- se filtro el tipo de metodo para verificar si es o no legitimo
=> update a middleware

resources/views/perfil/perfilUsuario.blade.php
DIS;EO EN LA APGINA PerfilUser.blade.php
=> Dise;no de user detalles

app/Http/Controllers/ProyectoController.php, routes/web.php
Arreglando Issues numero 8 de tutores
=> Lino final

app/Http/Middleware/SecurityMiddleware.php, routes/web.php
si el usuario no esta autentificado, no puede ingresar a otras partes del proyecto (modificando rutas) porque lo redirige a la pagina de bienvenida
=> protegiendo rutas si no esta autentificado el usuario

app/Http/Middleware/SecurityMiddleware.php
=> eliminando

app/Http/Controllers/ProyectoController.php
=> agregando lo anterior

public/storage/.gitignore, resources/views/usuarios/crearUsuario.blade.php
=> "actualizacion crear usuario"
